import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { FaGithubSquare } from "react-icons/fa";
import { FaFacebookSquare } from "react-icons/fa";
import { Tilt } from "react-tilt";
import { FiBriefcase } from "react-icons/fi";
import me from "./images/me.jpg";
import code from "./images/enigma.png";
import design from "./images/python_certification.jpg";
import consulting from "./images/reactjs.jpg";
import htmlcss from "./images/html_css.jpg";
import sql from "./images/SQL.png";
import ds from "./images/datascience.jpg";
import threed from "./images/3D.png";
import web1 from "./images/p1.png";
import web2 from "./images/p2.png";
import web3 from "./images/p3.png";
import web4 from "./images/p4.png";
import web5 from "./images/p5.png";
import web6 from "./images/p6.png";
import advnc from "./images/advnc1.png";
import advnc1 from "./images/advnc2.png";
import advnc2 from "./images/ci.png";
import advnc3 from "./images/emern.png";
import resumePDF from "./images/Ashutosh_resume.pdf";
import ButtonImage from "./images/me.jpg";
import github from "./images/github.png";
import link from "./images/click.jpg";
function App() {
  return (
    <div>
      <title>Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <main className=" bg-slate-50 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        {/* header section */}
        <section className="min-h-screen">
          {/* <nav className="py-10 mb-12 flex justify-between dark:text-white">
            
            <h1 className="font-burtons text-4xl font-extrabold">
              <span style={{ color: "red" }}>POR</span>
              <span style={{ color: "purple" }}>TFO</span>
              <span style={{ color: "blue" }}>LIO</span>
            </h1>

            <ul className="flex items-center">
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text-to-teal-900 text-white px-4 py-2 border-none rounded-md ml-8"
                  href={resumePDF}
                  // download="Ashutosh_resume.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  RESUME
                </a>
              </li>
            </ul>
          </nav> */}

          <nav className="py-5 md:py-10 mb-12 flex flex-col md:flex-row justify-between items-center md:items-start dark:text-white">
            <h1 className="font-burtons text-4xl font-extrabold text-center md:text-left">
              <span style={{ color: "red" }}>POR</span>
              <span style={{ color: "purple" }}>TFO</span>
              <span style={{ color: "blue" }}>LIO</span>
            </h1>

            <ul className="flex items-center justify-center md:justify-start mt-4 md:mt-0">
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text-to-teal-900 text-white px-4 py-2 border-none rounded-md ml-0 md:ml-8 mt-2 md:mt-0"
                  href={resumePDF}
                  // download="Ashutosh_resume.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  RESUME
                </a>
              </li>
              <li>
                <a
                  className="text-gray-900 dark:text-gray-300 px-4 py-2 ml-0 md:ml-4 mt-2 md:mt-0"
                  href="#work"
                >
                  WORK
                </a>
              </li>
              <li>
                <a
                  className="text-gray-900 dark:text-gray-300 px-4 py-2 ml-0 md:ml-4 mt-2 md:mt-0"
                  href="#projects"
                >
                  PROJECTS
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 font-medium dark:text-teal-400 md:text-6xl">
              <span className="animate-gradient-x text-red-600">Ashutosh</span>{" "}
              <span className="animate-pulse text-yellow-500">Raj</span>{" "}
              <span className="animate-gradient-x text-blue-600">Gupta</span>
            </h2>

            <h3 className="text-2xl py-2 dark:text-white md:text-3xl animate-bounce">
              FrontEnd Web Developer and Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl animate-fade-in">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3">
              <a href="https://github.com/AshutoshRajGupta" target="_blank">
                <FaGithubSquare className="animate-pulse text-gray-800 dark:text-gray-200 hover:text-teal-600" />
              </a>
              <a
                href="https://www.linkedin.com/in/ashutosh-raj-gupta-18230820b/"
                target="_blank"
              >
                <AiFillLinkedin className="animate-pulse text-blue-600 hover:text-blue-800" />
              </a>
              <a
                href="https://www.facebook.com/profile.php?id=100022615870474"
                target="_blank"
              >
                <FaFacebookSquare className="animate-pulse text-blue-800 hover:text-blue-900" />
              </a>
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-40 h-40 relative overflow-hidden mt-20 md:h-56 md:w-56">
              <img src={me} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        {/* work  */}
        <section className="py-10" id="work">
          <div className="container mx-auto">
            <h2 className="text-3xl font-bold text-center text-red-300 mb-8">
              WORK EXPERIENCE
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-green-200 rounded-lg shadow-white p-6 h-64 relative">
                <Tilt className="tilt">
                  <div className="flex items-center mb-4">
                    <FiBriefcase className="text-teal-600 mr-2" />
                    <h3 className="text-lg font-medium text-blue-500 dark:text-blue-800">
                      SOLAR SECURE SOLUTIONS
                    </h3>
                  </div>

                  <h4 className="text-base font-medium mb-2">
                    <span style={{ color: "red" }}>F</span>
                    <span style={{ color: "green" }}>U</span>
                    <span style={{ color: "blue" }}>L</span>
                    <span style={{ color: "red" }}>L</span>
                    <span style={{ color: "green" }}> </span>
                    <span style={{ color: "blue" }}>S</span>
                    <span style={{ color: "red" }}>T</span>
                    <span style={{ color: "green" }}>A</span>
                    <span style={{ color: "blue" }}>C</span>
                    <span style={{ color: "red" }}>K</span>
                    <span style={{ color: "green" }}> </span>
                    <span style={{ color: "blue" }}>W</span>
                    <span style={{ color: "red" }}>E</span>
                    <span style={{ color: "green" }}>B</span>
                    <span style={{ color: "blue" }}> </span>
                    <span style={{ color: "red" }}>D</span>
                    <span style={{ color: "green" }}>E</span>
                    <span style={{ color: "blue" }}>V</span>
                    <span style={{ color: "red" }}>E</span>
                    <span style={{ color: "green" }}>L</span>
                    <span style={{ color: "blue" }}>O</span>
                    <span style={{ color: "red" }}>P</span>
                    <span style={{ color: "green" }}>E</span>
                    <span style={{ color: "blue" }}>R</span>
                  </h4>
                  <p className="text-sm text-black dark:text-gray-900 font-bold">
                    Worked as a Web Developer and developed creative and
                    interactive websites. Worked with Monzen Sustainable team in
                    configuration of Web Projects. Worked on creating efficient
                    React and PHP components using different technologies like
                    React, Node.js, MySQL, HTML, CSS, PHP, JavaScript, and APIs.
                  </p>
                  <a
                    href="https://example.com"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="circle-button absolute top-2 right-2">
                      <img
                        src={ButtonImage}
                        alt="Button Image"
                        className="w-6 h-6"
                      />
                    </button>
                  </a>
                </Tilt>
              </div>

              <div className="bg-blue-200 rounded-lg shadow-2xl p-6 h-64 relative">
                <Tilt className="tilt">
                  <div className="flex items-center mb-4">
                    <FiBriefcase className="text-teal-600 mr-2" />
                    <h3 className="text-lg font-medium text-blue-500 dark:text-green-900">
                      MONZEN SUSTAINABLE DEVELOPMENT
                    </h3>
                  </div>

                  <h4 className="text-base font-medium mb-2">
                    <span style={{ color: "red" }}>W</span>
                    <span style={{ color: "green" }}>E</span>
                    <span style={{ color: "blue" }}>B</span>
                    <span style={{ color: "red" }}> </span>
                    <span style={{ color: "green" }}>D</span>
                    <span style={{ color: "blue" }}>E</span>
                    <span style={{ color: "red" }}>V</span>
                    <span style={{ color: "green" }}>E</span>
                    <span style={{ color: "blue" }}>L</span>
                    <span style={{ color: "red" }}>O</span>
                    <span style={{ color: "green" }}>P</span>
                    <span style={{ color: "blue" }}>E</span>
                    <span style={{ color: "red" }}>R</span>
                  </h4>

                  <p className="text-sm text-black dark:text-gray-900 font-bold">
                    Worked as a Web Developer and developed creative and
                    interactive websites. Worked with Monzen Sustainable team in
                    configuration of Web Projects. Worked on creating efficient
                    React and PHP components using different technologies like
                    React, Node.js, MySQL, HTML, CSS, PHP, JavaScript, and APIs.
                  </p>

                  <a
                    href="https://example.com"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="circle-button absolute top-2 right-2">
                      <img
                        src={ButtonImage}
                        alt="Button Image"
                        className="w-6 h-6"
                      />
                    </button>
                  </a>
                </Tilt>
              </div>
            </div>
          </div>
        </section>

        {/* certification  */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-blue-700 font-extrabold text-center">
              CERTIFICATIONS AND COURSES
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Throughout my career as a designer and developer, I have acquired
              valuable certifications and completed various courses to enhance
              my skills and knowledge.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="lg:w-1/3">
              <Tilt
                className="rounded-lg overflow-hidden tilt-container"
                options={{ max: 25, scale: 1.05 }}
              >
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                  <img src={htmlcss} width={300} height={100} />
                  <h3 className="text-lg font-medium pt-8 pb-2">HTML && CSS</h3>
                  <a
                    href="https://www.udemy.com/certificate/UC-8257aff3-1c38-4feb-835a-399d5c9c8b4e/"
                    target="_blank"
                    className="btn-primary mr-30 px-4 py-2 bg-teal-600 text-white border border-teal-600 hover:bg-teal-800 hover:border-teal-800"
                  >
                    visit
                  </a>
                  <h4 className="py-4 text-teal-600">Skills Gained</h4>
                  <ul className="text-gray-800 py-1">
                    <li>HTML</li>
                    <li>CSS</li>
                  </ul>
                </div>
              </Tilt>
            </div>

            <div className="lg:w-1/3">
              <Tilt
                className="rounded-lg overflow-hidden tilt-container"
                options={{ max: 25, scale: 1.05 }}
              >
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                  <img src={consulting} width={300} height={100} />
                  <h3 className="text-lg font-medium pt-8 pb-2">
                    REACTJS CERTIFICATION
                  </h3>
                  <a
                    href="https://www.udemy.com/certificate/UC-2b0e022c-a01e-4d43-a853-6e99b5a2a40e/"
                    target="_blank"
                    className="btn-primary mr-30 px-4 py-2 bg-teal-600 text-white border border-teal-600 hover:bg-teal-800 hover:border-teal-800"
                  >
                    visit
                  </a>
                  <h4 className="py-4 text-teal-600">Skills Gained</h4>
                  <ul className="text-gray-800 py-1">
                    <li>REACT COMPONENT</li>
                    <li>HOOKS IN REACT</li>
                    <li>EVENT HANDLING</li>
                  </ul>
                </div>
              </Tilt>
            </div>

            <div className="lg:w-1/3">
              <Tilt
                className="rounded-lg overflow-hidden tilt-container"
                options={{ max: 25, scale: 1.05 }}
              >
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                  <img src={design} width={300} height={100} />
                  <h3 className="text-lg font-medium pt-8 pb-2">
                    PYTHON COURSE
                  </h3>
                  <a
                    href="https://www.udemy.com/certificate/UC-e442c3b5-b993-4f05-9ca5-18b0881c2cce/"
                    target="_blank"
                    className="btn-primary mr-30 px-4 py-2 bg-teal-600 text-white border border-teal-600 hover:bg-teal-800 hover:border-teal-800"
                  >
                    visit
                  </a>
                  <h4 className="py-4 text-teal-600">Skills Gained</h4>
                  <ul className="text-gray-800 py-1">
                    <li>PYTHON BASICS</li>
                    <li>FRAMEWORKS</li>
                  </ul>
                </div>
              </Tilt>
            </div>
          </div>

          <div className="lg:flex gap-10">
            <div className="lg:w-1/3">
              <Tilt
                className="rounded-lg overflow-hidden tilt-container"
                options={{ max: 25, scale: 1.05 }}
              >
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                  <img src={ds} width={300} height={100} />
                  <h3 className="text-lg font-medium pt-8 pb-2">
                    DATASCIENCE WITH PYTHON
                  </h3>
                  <a
                    href="https://www.udemy.com/certificate/UC-06476e45-241e-4d52-a89f-d2c29c067f41/"
                    target="_blank"
                    className="btn-primary mr-30 px-4 py-2 bg-teal-600 text-white border border-teal-600 hover:bg-teal-800 hover:border-teal-800"
                  >
                    visit
                  </a>
                  <h4 className="py-4 text-teal-600">Skills Gained</h4>
                  <ul className="text-gray-800 py-1">
                    <li>NUMPY & PANDAS</li>
                    <li>MATPLOTLIB</li>
                  </ul>
                </div>
              </Tilt>
            </div>

            <div className="lg:w-1/3">
              <Tilt
                className="rounded-lg overflow-hidden tilt-container"
                options={{ max: 25, scale: 1.05 }}
              >
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                  <img src={sql} width={300} height={100} />
                  <h3 className="text-lg font-medium pt-8 pb-2">
                    SQL COURSE CERTIFICATION
                  </h3>
                  <a
                    href="https://www.sololearn.com/certificates/CT-CMYLLQGB"
                    target="_blank"
                    className="btn-primary mr-30 px-4 py-2 bg-teal-600 text-white border border-teal-600 hover:bg-teal-800 hover:border-teal-800"
                  >
                    visit
                  </a>
                  <h4 className="py-4 text-teal-600">Skills Gained</h4>
                  <ul className="text-gray-800 py-1">
                    <li>MYSQl</li>
                    <li>BUILDING DATABASE</li>
                  </ul>
                </div>
              </Tilt>
            </div>

            <div className="lg:w-1/3">
              <Tilt
                className="rounded-lg overflow-hidden tilt-container"
                options={{ max: 25, scale: 1.05 }}
              >
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                  <img src={code} width={300} height={100} />
                  <h3 className="text-lg font-medium pt-8 pb-2">ENIGMA</h3>
                  <a
                    href=""
                    target="_blank"
                    className="btn-primary mr-30 px-4 py-2 bg-teal-600 text-white border border-teal-600 hover:bg-teal-800 hover:border-teal-800"
                  >
                    visit
                  </a>

                  <h4 className="py-4 text-teal-600">Skills Gained</h4>
                  <ul className="text-gray-800 py-1">
                    <li>LOGIC BUILDING</li>
                    <li>PROBLEM-SOLVING</li>
                  </ul>
                </div>
              </Tilt>
            </div>
          </div>
        </section>

        {/* projects  */}
        <section className="py-10" id="projects">
          <div>
            <h3 className="text-3xl py-1 font-bold dark:text-green-200 text-center">
              PROJECTS
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for{" "}
              <span className="text-teal-500">agencies</span>, consulted for{" "}
              <span className="text-teal-500">startups</span>, and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of services, including brand design,
              programming, and teaching.
            </p>
          </div>

          <div className="py-10">
            <h4 className="text-3xl py-2 mb-8 font-bold dark:text-white text-center font-extrabold text-blue-400 animate-pulse">
              BEGINNER
            </h4>

            {/* beginner  */}
            <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={threed}
                    alt="Project 2"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    3D PORTFOLIO WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/3D_portfolio"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://portfo-one.vercel.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button  ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  A 3D portfolio website made using REACTJS and 3d animation
                  <br />
                  users acn show there projects and works with this 3D template.
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>

              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={web1}
                    alt="Project 1"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    TODO WEB WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/todo_firebase"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button  ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://todo-firebase-mu.vercel.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button  ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  ToDo Application made using ReactJs with localStorage.
                  <br />
                  Users can edit, add, delete, and mark todos as complete.
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>
            </div>
          </div>

          <div className="py-10">
            <h4 className="text-3xl py-2 mb-8 font-bold dark:text-white text-center font-extrabold text-blue-900 animate-pulse">
              INTERMEDIATE
            </h4>

            {/* intermediate  */}
            <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={web3}
                    alt="Project 3"
                  />
                </Tilt>
                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    ECOMMERCE PHP WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/ecommerce_php"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button  ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://github.com/AshutoshRajGupta/ecommerce_php"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button  ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  Ecommerce website made using PHP, MySQL, and HTML.
                  <br />
                  Users can login, sign in, add items to the cart, and proceed
                  to payment.
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>

              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={web4}
                    alt="Project 4"
                  />
                </Tilt>
                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    EVENT MANAGEMENT WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/WTL_MIni_Project"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://github.com/AshutoshRajGupta/WTL_MIni_Project"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  Event management system made for college studentto register
                  and<br></br> aprticipate in event.User can register then login
                  go payment fees etc.{" "}
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>

              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={web5}
                    alt="Project 5"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    MAP2CODE LEARNING WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/map2proCoder"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://map2procoder.vercel.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  A website which describes the learning path for different
                  domains
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>

              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={web6}
                    alt="Project 6"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    EXPENSE BUDGET WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/expense_try"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://expense-try.vercel.app/"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  Budget app made using reactjs and vitejs to manage your budget
                  and expense
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>
            </div>
          </div>

          {/* advanced  */}
          <div className="py-10">
            <h4 className="text-3xl py-2 mb-8 font-bold dark:text-white text-center font-extrabold text-blue-900 animate-pulse">
              ADVANCED
            </h4>

            <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={advnc2}
                    alt="Project 3"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    CREATIVE INSIGHTS WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/Creative_Insights"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://github.com/AshutoshRajGupta/Creative_Insights"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  A Full stack NextJS website made using mongodb reactjs NextJS
                  <br></br> where user can add blog and his Portfolio work user
                  can easily<br></br> authenticate through google
                  authenticationhe can delete the<br></br> blogs and all the
                  blogs will be save on the database.
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>

              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={advnc}
                    alt="Project 3"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    WORKOUT STATS WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/workout_mern"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://github.com/AshutoshRajGupta/workout_mern"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  A mern stack workout website made using mongodb reactjs
                  express nodejs where user can add information about his
                  workout and can<br></br> add information about his workout and
                  he can delete the workout<br></br> and all the workouts will
                  be save on the database.
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>

              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={advnc3}
                    alt="Project 3"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    ECOMMERCE MERN WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/ecommerce"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://github.com/AshutoshRajGupta/ecommerce"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  A mern stack Ecommerce website made using mongodb reactjs
                  express<br></br> nodejs where user can add information about
                  his products and he can<br></br> delete the products and all
                  the products will be save on the database.
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>

              <div className="basis-1/3 flex-1">
                <Tilt
                  className="rounded-lg overflow-hidden tilt-container"
                  options={{ max: 25, scale: 1.05 }}
                >
                  <img
                    className="rounded-lg object-cover"
                    width={500}
                    height={250}
                    layout="responsive"
                    src={advnc1}
                    alt="Project 3"
                  />
                </Tilt>

                <div className="flex items-center">
                  <p className="text-lg py-2 font-medium text-blue-900 dark:text-blue-400">
                    CRYPTOCURRENCY STATS WEBSITE
                  </p>

                  <a
                    href="https://github.com/AshutoshRajGupta/cryptoworld"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-20">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={github}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                  <a
                    href="https://github.com/AshutoshRajGupta/cryptoworld"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    <button className="rounded-full w-10 h-10 bg-blue-500 hover:bg-blue-600 focus:bg-blue-600 tilt-button project-button ml-12">
                      <img
                        className="w-full h-full object-cover rounded-full"
                        src={link}
                        alt="GitHub Icon"
                      />
                    </button>
                  </a>
                </div>

                <p className="text-red-600">
                  A crypto currency website made using ReactJs and rapid API
                  through <br></br>which users can easily acess the data of
                  every crypto currency and <br></br> user can get the data
                  through visiual representation.
                </p>
                <div className="flex justify-center mt-4"></div>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-blue-200 py-10">
          <div className="container mx-auto">
            <h2 className="text-3xl font-bold text-center text-gray-800 animate-pulse">
              CONNECT WITH US
            </h2>
            <div className="flex justify-center mt-8">
              <a
                href="https://www.linkedin.com/in/ashutosh-raj-gupta-18230820b/"
                className="btn-primary mr-10 bg-blue-600 hover:bg-blue-800 px-6 py-3 animate-bounce"
              >
                LINKEDIN
              </a>
              <a
                href="https://github.com/AshutoshRajGupta"
                className="btn-secondary mr-10 bg-gray-800 text-white hover:bg-gray-900 px-6 py-3 animate-pulse"
              >
                GITHUB
              </a>
              <a
                href="#"
                className="btn-secondary mr-10 bg-red-600 hover:bg-red-800 px-6 py-3 animate-spin"
              >
                MAIL
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

export default App;
